# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luciano/Dropbox/Mu-P_Mapping

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luciano/Dropbox/Mu-P_Mapping

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luciano/Dropbox/Mu-P_Mapping/CMakeFiles /home/luciano/Dropbox/Mu-P_Mapping/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luciano/Dropbox/Mu-P_Mapping/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mapMu-P

# Build rule for target.
mapMu-P: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapMu-P
.PHONY : mapMu-P

# fast build rule for target.
mapMu-P/fast:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/build
.PHONY : mapMu-P/fast

#=============================================================================
# Target rules for targets named mapMu-Ptests

# Build rule for target.
mapMu-Ptests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapMu-Ptests
.PHONY : mapMu-Ptests

# fast build rule for target.
mapMu-Ptests/fast:
	$(MAKE) -f CMakeFiles/mapMu-Ptests.dir/build.make CMakeFiles/mapMu-Ptests.dir/build
.PHONY : mapMu-Ptests/fast

src/Reference_Data.o: src/Reference_Data.cpp.o

.PHONY : src/Reference_Data.o

# target to build an object file
src/Reference_Data.cpp.o:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/Reference_Data.cpp.o
.PHONY : src/Reference_Data.cpp.o

src/Reference_Data.i: src/Reference_Data.cpp.i

.PHONY : src/Reference_Data.i

# target to preprocess a source file
src/Reference_Data.cpp.i:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/Reference_Data.cpp.i
.PHONY : src/Reference_Data.cpp.i

src/Reference_Data.s: src/Reference_Data.cpp.s

.PHONY : src/Reference_Data.s

# target to generate assembly for a file
src/Reference_Data.cpp.s:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/Reference_Data.cpp.s
.PHONY : src/Reference_Data.cpp.s

src/data_handling.o: src/data_handling.cpp.o

.PHONY : src/data_handling.o

# target to build an object file
src/data_handling.cpp.o:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/data_handling.cpp.o
.PHONY : src/data_handling.cpp.o

src/data_handling.i: src/data_handling.cpp.i

.PHONY : src/data_handling.i

# target to preprocess a source file
src/data_handling.cpp.i:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/data_handling.cpp.i
.PHONY : src/data_handling.cpp.i

src/data_handling.s: src/data_handling.cpp.s

.PHONY : src/data_handling.s

# target to generate assembly for a file
src/data_handling.cpp.s:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/data_handling.cpp.s
.PHONY : src/data_handling.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/peng_robinson.o: src/peng_robinson.cpp.o

.PHONY : src/peng_robinson.o

# target to build an object file
src/peng_robinson.cpp.o:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/peng_robinson.cpp.o
.PHONY : src/peng_robinson.cpp.o

src/peng_robinson.i: src/peng_robinson.cpp.i

.PHONY : src/peng_robinson.i

# target to preprocess a source file
src/peng_robinson.cpp.i:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/peng_robinson.cpp.i
.PHONY : src/peng_robinson.cpp.i

src/peng_robinson.s: src/peng_robinson.cpp.s

.PHONY : src/peng_robinson.s

# target to generate assembly for a file
src/peng_robinson.cpp.s:
	$(MAKE) -f CMakeFiles/mapMu-P.dir/build.make CMakeFiles/mapMu-P.dir/src/peng_robinson.cpp.s
.PHONY : src/peng_robinson.cpp.s

tests/tests_main.o: tests/tests_main.cpp.o

.PHONY : tests/tests_main.o

# target to build an object file
tests/tests_main.cpp.o:
	$(MAKE) -f CMakeFiles/mapMu-Ptests.dir/build.make CMakeFiles/mapMu-Ptests.dir/tests/tests_main.cpp.o
.PHONY : tests/tests_main.cpp.o

tests/tests_main.i: tests/tests_main.cpp.i

.PHONY : tests/tests_main.i

# target to preprocess a source file
tests/tests_main.cpp.i:
	$(MAKE) -f CMakeFiles/mapMu-Ptests.dir/build.make CMakeFiles/mapMu-Ptests.dir/tests/tests_main.cpp.i
.PHONY : tests/tests_main.cpp.i

tests/tests_main.s: tests/tests_main.cpp.s

.PHONY : tests/tests_main.s

# target to generate assembly for a file
tests/tests_main.cpp.s:
	$(MAKE) -f CMakeFiles/mapMu-Ptests.dir/build.make CMakeFiles/mapMu-Ptests.dir/tests/tests_main.cpp.s
.PHONY : tests/tests_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... mapMu-P"
	@echo "... edit_cache"
	@echo "... mapMu-Ptests"
	@echo "... src/Reference_Data.o"
	@echo "... src/Reference_Data.i"
	@echo "... src/Reference_Data.s"
	@echo "... src/data_handling.o"
	@echo "... src/data_handling.i"
	@echo "... src/data_handling.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/peng_robinson.o"
	@echo "... src/peng_robinson.i"
	@echo "... src/peng_robinson.s"
	@echo "... tests/tests_main.o"
	@echo "... tests/tests_main.i"
	@echo "... tests/tests_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

